### ISSUE TITLE
Publishing: Blog post for using python template GCSToBigQuery

### ISSUE THREAD

**Issue by shashank-google** [GoogleCloudPlatform/dataproc-templates#105]

**Comment by shashank-google** [comment]
@ppaglilla Any updates ?

**Comment by ppaglilla** [comment]
I'll be sharing a draft later today with the team to start reviewing

**Comment by shashank-google** [comment]
@ppaglilla any updates on this ?

**Comment by ppaglilla** [comment]
Published the [blog post](https://medium.com/@ppaglilla/getting-started-with-dataproc-serverless-pyspark-templates-e32278a6a06e)!
