### ISSUE TITLE
[NewTemplate] [Python] Databases to GCS in Avro / Orc / Parquet etc formats

### ISSUE THREAD

**Issue by shashank-google** [GoogleCloudPlatform/dataproc-templates#107]
Expected support for databases:
1. MySQL
2. Postgresql
3. MS-SQL Server

**Comment by shashank-google** [comment]
@jirilmongeorge-google any updates ?

**Comment by varunika** [comment]
I would be working on this starting today

**Comment by varunika** [comment]
Changes are ready to push. Waiting for access to the repo.
