### ISSUE TITLE
Bug: Templates not compiling and launching with Java 17, 18

### ISSUE THREAD

**Issue by shashank-google** [GoogleCloudPlatform/dataproc-templates#127]
Templates not compiling with Java 17 and Java 18.

**Comment by shashank-google** [comment]
I verified, this is an issue at least for Java version 17 and 18.
The tests do not compile for some reason, needs to be investigated and fixed.

**Comment by poojabasker20** [comment]
As per https://cloud.google.com/dataproc-serverless/docs/concepts/versions/spark-runtime-versions, Spark runtime version 2.0 supports Spark 3.3.1 and Java 17. It also requires Scala 2.13 which is not binary compatible with Spark 2.12 (what is currently being used). Certain dependencies ([spark-streaming-pubsub](https://mvnrepository.com/artifact/org.apache.bahir/spark-streaming-pubsub) & [spark-cassandra-connector](https://mvnrepository.com/artifact/com.datastax.spark/spark-cassandra-connector)) still do not have support for Scala 2.13 which causes an error when the Scala version is upgraded.

**Comment by shashank-google** [comment]
@poojabasker20 I looked into this you are right that scala 2.13 is missing for both.
Can we use scala 2.12 for these two libraries and 2.13 for rest ?
@vanshaj-bhatia @balajiss2 what do you think ?

If that is not possible then maybe we can close this git issue saying it cannot be fixed.

**Comment by vanshaj-bhatia** [comment]
Since Spark runtime 2.x primarily supports Scala 2.13, I believe it makes sense to use Scala 2.13 and just keep version 2.12 for these two dependencies.

**Comment by poojabasker20** [comment]
A few solutions I was able to find for this issue -
1. restructure the project so that there are 2 modules, configure scala maven plugin to use different versions of scala for different modules
2. create a fat jar with multiple versions of scala (might lead to a large jar file)
3. make use of maven profiles for different versions of scala, but correct profiles have to be activated during build

**Comment by vanshaj-bhatia** [comment]
Thanks Pooja! I think implementing any of the above points would add much complexity to the build and the project structure. I think we should not pursue this change right now and can close this issue. 
@shashank-google what are your thoughts?

**Comment by shashank-google** [comment]
@vanshaj-bhatia I am good with closing this issue if solutions are unnecessarily complex.
Just calling out, we are already doing fat jar i.e. option (2)

**Comment by poojabasker20** [comment]
Closing this issue as some of the dependencies are not forward compatible with Scala 2.13 (HBaseTableCatalog class of hbase-spark requires scala.Serializable which is not present in Scala 2.13).
