### ISSUE TITLE
[Publishing] BigQueryToGCS pyspark

### ISSUE THREAD

**Issue by shashank-google** [GoogleCloudPlatform/dataproc-templates#131]
1. Multiple formats avro / parquet / orc etc
2. Incremental loads
3. Large data volumnes

**Comment by surjits254** [comment]
Created the blog
https://medium.com/@surjitsh/moving-data-from-bigquery-to-gcs-using-gcp-dataproc-serverless-and-pyspark-f6481b86bcd1
Will close the issue once the blog is added to cloud community publication
