### ISSUE TITLE
[hardening] [java] GCSToJDBC

### ISSUE THREAD

**Issue by shashank-google** [GoogleCloudPlatform/dataproc-templates#148]
For RDBMS, hardening goal can be 100GB

**Comment by abhijat-gupta** [comment]
Hardening is in progress. So far I am able to tune the job run for upto 10GB of data. Only optimisation is the repartitioning the  spark dataset before writing it to JDBC. I am able to tune the load time by 30 minutes for 10GB of data. I am still working on it to further decrease the load time.

**Comment by abhijat-gupta** [comment]
I also tried to tune the spark job with some parameters like # executors, cores, etc., but since it is dataproc serverless, it will auto scale it once the job runs. So tuning spark parameters will not help here.

**Comment by abhijat-gupta** [comment]
As discussed with Shashank last week, I am setting up an AlloyDB cluster and use that as JDBC for testing 100GB load from GCS to postgres.

**Comment by shashank-google** [comment]
Many thanks Abhijat for the awesome work.
In my previous tests dataproc templates have taken ~10 mins for a 30GB
database to AlloyDB.

**Comment by abhijat-gupta** [comment]
Unable to see my last comment here, hence writing it again - 
I am able to bring down the load time from ~3 hours to 1 hour 15 min for 100 GB. Have tweaked the code to accept another argument for custom spark partitions in the bin command.

**Comment by abhijat-gupta** [comment]
@shashank-google : Hey Shashank. The ask is to test this template for 100GB. I am done with testing for the same. I will go ahead and commit the code and raise merge request.
Thank you.

**Comment by abhijat-gupta** [comment]
@hhasija : [PR](https://github.com/GoogleCloudPlatform/dataproc-templates/pull/450) raised. Please review and merge
