### ISSUE TITLE
FR: HiveToBigQuery template support Database migration

### ISSUE THREAD

**Issue by snrssc** [GoogleCloudPlatform/dataproc-templates#15]
HiveToBigQuery currently supports single table migration. Add the following features to the template, 

1. Ability to Migrate entire Database (All tables in the database).
2.  Maintain the state for handling features.  Ability to re-run from the failed step.
3. Add Summary Metrics . Record how many rows were migrated and load date_time.

**Comment by shashank-google** [comment]
@shubhamgoogle How are we making progress at this ?
Just trowing an idea, that you can potentially develop a python notebook to orchestrate this solution.
https://github.com/GoogleCloudPlatform/dataproc-templates/blob/main/python/notebooks/README.md

**Comment by shubhamgoogle** [comment]
Hi @shashank-google , Things are on track. Almost done with parallel job execution to migrate whole database.
Next are: Adding Summary metrics in BQ table and handling partitioned tables.
