### ISSUE TITLE
[publish] blog on DataplexGCStoBQ

### ISSUE THREAD

**Issue by shashank-google** [GoogleCloudPlatform/dataproc-templates#153]

**Comment by ClementineJoe** [comment]
Hi Franklin, I am currently unassigning you since there is no updates for a long time. If you want to contribute please comeback and self assign.

**Comment by forksumit** [comment]
Noticed, There's already a blog published for same by Vasu: https://medium.com/google-cloud/using-dataproc-serverless-to-migrate-your-dataplex-gcs-data-to-bigquery-1e47bc8de74c

Closing this issue
