### ISSUE TITLE
[NewTemplate] [Python] JDBC to JDBC

### ISSUE THREAD

**Issue by shashank-google** [GoogleCloudPlatform/dataproc-templates#154]
Template should support read partitioning

**Comment by Naveenkm13** [comment]
@shashank-google  Wanted to clarify the requirement. We need to read data from partitioned table  on particular partition filter and able to write on non-partitioned table via jdbc correct?

**Comment by shashank-google** [comment]
Take a look at JDBCToGCS's Read Portion https://github.com/GoogleCloudPlatform/dataproc-templates/blob/main/java/src/main/java/com/google/cloud/dataproc/templates/jdbc/README.md#2-jdbc-to-gcs
Instead of GCS for write sink, write to JDBC.
