### ISSUE TITLE
[NewTemplate][Java] GCSToBigTable

### ISSUE THREAD

**Issue by shashank-google** [GoogleCloudPlatform/dataproc-templates#157]
similar to python template

**Comment by shashank-google** [comment]
HI @anish97IND If you are not working on this gitissue, can you please un-assign yourself.

**Comment by anish97IND** [comment]
Hi @shashank-google , I have completed the coding part but was facing issue with a dependency. Hence, was unable to raise PR for it. However, I will un-assign myself, will revert back if I find a triage.
