### ISSUE TITLE
Explore Vertex AI / Jupyter Notebooks for end to end migration solutions

### ISSUE THREAD

**Issue by shashank-google** [GoogleCloudPlatform/dataproc-templates#170]
- Attempt to launch java templates
- Launch python templates
-

**Comment by ppaglilla** [comment]
We're working in a solution that will allow users to easily work with Python templates programatically.

The objective is to provide an pure-python interface that allows:

1. Running templates in a local installation of Spark (e.g. for users running on Dataproc Serverless Sessions)
2. Triggering Dataproc Serverless Batch jobs that run a template
3. Integrating the templates with Vertex AI (without needing to clone and build the project manually, which is how it stands right now)

That interface would be very easy to use in Python notebook or other Python environment (e.g. users that want to trigger a template from Apache Airflow).

As per the possibility of launching Java templates, we'd need to dig deeper into options. Of course, cloning the repository and triggering the templates using the `start.sh` is always an option. However; that requires the notebook's environment to have Java + Maven, which might not be very common.
