### ISSUE TITLE
[Hardening] Pub/Sub to GCS template

### ISSUE THREAD

**Issue by vanshaj-bhatia** [GoogleCloudPlatform/dataproc-templates#176]
Testing templates with up to 5TB of data and up to 1 GBs throughput

**Comment by pniralakeri** [comment]
@vanshaj-bhatia I've recorded my observations [here](https://docs.google.com/document/d/16riET-NrF21-I72b6UwehoczCU_4VONUA_dukocVKMk/edit#heading=h.vxz121uexhtp). PTAL

**Comment by hhasija** [comment]
Hardening details are entered into the hardening doc successfully. We are good to close this issue.
