### ISSUE TITLE
[java] Tech Debt - Add JUnit tests for templates

### ISSUE THREAD

**Issue by shashank-google** [GoogleCloudPlatform/dataproc-templates#206]
Add JUnit tests for below templates, you may use [HiveToGCSTest.java](https://github.com/GoogleCloudPlatform/dataproc-templates/blob/main/java/src/test/java/com/google/cloud/dataproc/templates/hive/HiveToGCSTest.java) as example.
Goal is write unit test for all the business logic before spark session is created.

[JDBCToGCS.java](https://github.com/GoogleCloudPlatform/dataproc-templates/blob/main/java/src/main/java/com/google/cloud/dataproc/templates/jdbc/JDBCToGCS.java)
[JDBCToBigQuery.java](https://github.com/GoogleCloudPlatform/dataproc-templates/blob/main/java/src/main/java/com/google/cloud/dataproc/templates/jdbc/JDBCToBigQuery.java)
[SpannerToGCS.java](https://github.com/GoogleCloudPlatform/dataproc-templates/blob/main/java/src/main/java/com/google/cloud/dataproc/templates/databases/SpannerToGCS.java)
[DataplexGCStoBQ.java](https://github.com/GoogleCloudPlatform/dataproc-templates/blob/main/java/src/main/java/com/google/cloud/dataproc/templates/dataplex/DataplexGCStoBQ.java)

**Comment by poojabasker20** [comment]
JUnit tests for [JDBCToGCS.java](https://github.com/GoogleCloudPlatform/dataproc-templates/blob/main/java/src/main/java/com/google/cloud/dataproc/templates/jdbc/JDBCToGCS.java) and [JDBCToBigQuery.java](https://github.com/GoogleCloudPlatform/dataproc-templates/blob/main/java/src/main/java/com/google/cloud/dataproc/templates/jdbc/JDBCToBigQuery.java) have been added as part of issue https://github.com/GoogleCloudPlatform/dataproc-templates/issues/464

**Comment by hhasija** [comment]
Closing out this issue, as different folks are working on different unit tests. Thus, created different issues separately for different templates :-

https://github.com/GoogleCloudPlatform/dataproc-templates/issues/464

https://github.com/GoogleCloudPlatform/dataproc-templates/issues/466

https://github.com/GoogleCloudPlatform/dataproc-templates/issues/530
