### ISSUE TITLE
[python] publish dataproc templates in pypi package

### ISSUE THREAD

**Issue by shashank-google** [GoogleCloudPlatform/dataproc-templates#208]

**Comment by sjlva** [comment]
Hi, I want work on that issue. Could you please add more details?

Would you like an dataproc-template pypi package to execute those templates in CLI? Like:

After 
```
pip install dataproc_templates
```

Being able to execute something like that?
```
dataproc_templates \
    --template JDBCToGCS \
    --staging_location gs://<bucket-name> 
    --arg1 arg1 \
    --... ... \
    --args args
```

**Comment by ankuljain09** [comment]
Hi, I am interested in this one, please assign if this is available.

**Comment by shashank-google** [comment]
Done
