### ISSUE TITLE
[new-template][java] snowflake to gcs template

### ISSUE THREAD

**Issue by shashank-google** [GoogleCloudPlatform/dataproc-templates#209]

**Comment by shashank-google** [comment]
Adding @snrssc for snowflake experience.

**Comment by vanshaj-google** [comment]
@snrssc @shashank-google Raised a PR. Please review whenever possible. Used Snowflake-Spark Connector for the same.

**Comment by vanshaj-bhatia** [comment]
Hardening is failing when the dataset size is larger than ~1.5TB.
Error Message:
`Exception in thread "main" net.snowflake.client.jdbc.SnowflakeSQLException: JDBC driver encountered communication error. Message: Exception encountered when executing statement: Premature end of chunk coded message body: closing chunk expected.`

Raised an issue https://github.com/snowflakedb/snowflake-jdbc/issues/1127 at [snowflake-jdbc](https://github.com/snowflakedb/snowflake-jdbc).
