### ISSUE TITLE
[bug][python] Usage Tracking missing for most of the python templates

### ISSUE THREAD

**Issue by shashank-google** [GoogleCloudPlatform/dataproc-templates#213]
Only GCSTOBigQuery python template is being tracked in the [dashboard](https://datastudio.google.com/c/reporting/835976c7-e1dd-411f-9dee-4f079554b544/page/D0BUB?params=%7B%22df43%22:%22include%25EE%2580%25800%25EE%2580%2580IN%25EE%2580%2580google-pso-dataproc-templates%22%7D) 
Rest all of the python templates need to be fixed so that usage is tracked.

**Comment by ClementineJoe** [comment]
Hi Nilo Freitas , Could you please update the progress of the issue , Thanks in Advance
