### ISSUE TITLE
Rename HIVE package to hive

### ISSUE THREAD

**Issue by ajayydv** [GoogleCloudPlatform/dataproc-templates#240]
Rename HIVE package under python notebooks to hive

https://github.com/GoogleCloudPlatform/dataproc-templates/tree/hive2bq/python/notebooks/HIVE

**Comment by rohanshankar** [comment]
Could you clarify the problem? Do you want to rename it to hive so that it reads
https://github.com/GoogleCloudPlatform/dataproc-templates/tree/hive2bq/python/notebooks/hive ?
