### ISSUE TITLE
[jenkins] Update existing jenkins job(s) to be run manually against any branch

### ISSUE THREAD

**Issue by shashank-google** [GoogleCloudPlatform/dataproc-templates#242]
Update existing jenkins job(s) for build and integration test
Such that when run manually, it should show a drop down to select branch from github to build the code (default should be main branch).

**Comment by hhasija** [comment]
This feature has been enabled now on Jenkins UI Dashboard. @shashank-google Please check once and do let us know, if we are good to close this issue.

**Comment by shashank-google** [comment]
Many thanks @vanshaj-bhatia @hhasija for doing this.
Please update the build job(s) for java and python as well.

**Comment by vanshaj-bhatia** [comment]
@shashank-google Updated the build jobs for Python & Java. We are good to close this issue.

**Comment by shashank-google** [comment]
sounds good thanks.
