### ISSUE TITLE
[java] Update dependency 

### ISSUE THREAD

**Issue by shashank-google** [GoogleCloudPlatform/dataproc-templates#280]
Security venerability, update following dependency to following.
Ensure build and tests are working.

<dependency>
  <groupId>org.apache.hadoop</groupId>
  <artifactId>hadoop-common</artifactId>
  <version>3.2.4</version>
</dependency>

**Comment by ishu-thakur** [comment]
@shashank-google i want to work on this if this issue is still open ?

**Comment by shashank-google** [comment]
@ishu-thakur it was fixed already
