### ISSUE TITLE
[publish] Blog on GCSToJDBC

### ISSUE THREAD

**Issue by hhasija** [GoogleCloudPlatform/dataproc-templates#297]

**Comment by sjlva** [comment]
@hhasija could you assign it to me? I do not have permissions to self assign issues.

**Comment by hhasija** [comment]
> @hhasija could you assign it to me? I do not have permissions to self assign issues.

Done

**Comment by ClementineJoe** [comment]
HI Rafael Silva , Could you please update the progress of this issue,Thanks in advance

**Comment by hhasija** [comment]
@sjlva Could you please update the progress of this issue,Thanks in advance
