### ISSUE TITLE
[publish] Blog on HBaseToGCS

### ISSUE THREAD

**Issue by hhasija** [GoogleCloudPlatform/dataproc-templates#299]

**Comment by ClementineJoe** [comment]
Hi Neha, could you please provide updates about the issue progress

**Comment by vanshaj-bhatia** [comment]
Hi @nehamodgil, Since there haven't been updates from you for a while, unassigning you from this task.

**Comment by nehamodgil** [comment]
> 
@vanshaj-bhatia The blogpost was published last year in February 2023 - https://medium.com/@nehamodgil_21070/dataproc-serverless-for-exporting-large-data-files-from-hbase-to-gcs-d89057279512 

Let me know if I have missed anything.

**Comment by vanshaj-bhatia** [comment]
@nehamodgil Assigning back to you and closing the issue.
