### ISSUE TITLE
[publish] Blog on JDBCToGCS

### ISSUE THREAD

**Issue by hhasija** [GoogleCloudPlatform/dataproc-templates#303]

**Comment by sjlva** [comment]
@hhasija could you assign it to me?

**Comment by hhasija** [comment]
> @hhasija could you assign it to me?

Done

**Comment by shashank-google** [comment]
@sjlva any updates?

**Comment by sjlva** [comment]
I'll work on that this weekend.On Sep 28, 2022 6:24 AM, Shashank Agarwal ***@***.***> wrote:
@sjlva any updates?

**Comment by hhasija** [comment]
The issue is duplicate of :- https://github.com/GoogleCloudPlatform/dataproc-templates/issues/155
Thus, closing this out, as it is already done.
