### ISSUE TITLE
[documentation][bug] Python BQToGCS Example Submission 

### ISSUE THREAD

**Issue by shashank-google** [GoogleCloudPlatform/dataproc-templates#330]
Python BQToGCS [Example Submission](https://github.com/GoogleCloudPlatform/dataproc-templates/tree/main/python/dataproc_templates/bigquery#example-submission) needs to be updated with absolute values in the example.

**User feedback as below:**

The templates are great, thx for building them. One thing I noticed, the BQ to GCS PySpark template README makes it look like you can append a path to the GCS staging location, but when I try that it gives me an error until I just put the bucket name.

README is [here](https://github.com/GoogleCloudPlatform/dataproc-templates/tree/main/python/dataproc_templates/bigquery)

Example includes the following:
export GCS_STAGING_LOCATION=<gcs-staging-bucket-folder>

That makes me think I could put a GCS bucket and folder, but when I do that, it gives the following error:
ERROR: (gcloud.beta.dataproc.batches.submit.pyspark) HTTPError 400: Invalid bucket name: 'gm-sls-data/stage'

If I just submit it with the staging location as gs://gm-sls-data then it works as expected.

**Comment by arindam-google** [comment]
The same issue exists in [Java JDBC to BQ](https://github.com/GoogleCloudPlatform/dataproc-templates/blob/main/java/src/main/java/com/google/cloud/dataproc/templates/jdbc/README.md).

**Comment by tanyarw** [comment]
Will extend this for all the templates.
