### ISSUE TITLE
[automation] Explore CI/CD for Jupyter Notebooks

### ISSUE THREAD

**Issue by shradha-tyagi** [GoogleCloudPlatform/dataproc-templates#331]

**Comment by tanyarw** [comment]
In Progress - discussion pending

**Comment by tanyarw** [comment]
Discussed changes with @NiloFreitas, currently working on it

**Comment by tanyarw** [comment]
Closed with this [merge commit](https://github.com/GoogleCloudPlatform/dataproc-templates/pull/766#:~:text=LGTM-,Merge%20pull%20request,-%23766%20from%20GoogleCloudPlatform)
