### ISSUE TITLE
[publishing] [notebook] MySQLToSpanner notebook publish blogpost 

### ISSUE THREAD

**Issue by shashank-google** [GoogleCloudPlatform/dataproc-templates#347]
Publish a blogpost with screenshot explaining deployment and execution of MySQLToSpanner notebook

**Comment by surjits254** [comment]
Draft version created, currently in review

**Comment by surjits254** [comment]
Published : https://medium.com/google-cloud/mysql-to-cloud-spanner-migrate-mysql-database-to-cloud-spanner-using-vertex-ai-notebooks-and-gcp-ad7d2ed8a317
