### ISSUE TITLE
How can we capture full load as well as the cdc via spark on dataproc ?

### ISSUE THREAD

**Issue by Rstar1998** [GoogleCloudPlatform/dataproc-templates#354]
I had a look on this script [https://github.com/GoogleCloudPlatform/dataproc-templates/blob/main/python/dataproc_templates/mongo/mongo_to_gcs.py]. But it seems that this script does a full load of all collections in a mongodb database. Is there any way such that we can modify this script and also capture the cdc data ?

**Comment by NiloFreitas** [comment]
Hi Rstar1998. The Mongo to GCS template does a migration of a specific collection that you pass as a parameter when submitting the template. It does not do a full load of all collections. About CDC, it is not the focus of these templates.
