### ISSUE TITLE
[jenkins] Create integration test automation for CassandraToBQ template

### ISSUE THREAD

**Issue by shashank-google** [GoogleCloudPlatform/dataproc-templates#355]

**Comment by tanyarw** [comment]
<img width="1903" alt="Screenshot 2023-01-17 at 11 24 20 AM" src="https://user-images.githubusercontent.com/51485771/212820519-4dc7de75-d047-46cf-ae7b-f0c64eb26583.png">


Added CassandraToBQ test.
