### ISSUE TITLE
[Notebook] Create first notebook using Spark Sessions in Vertex AI

### ISSUE THREAD

**Issue by NiloFreitas** [GoogleCloudPlatform/dataproc-templates#379]
Create the first implementation of a notebook focusing on the AI/ML use case, leveraging Dataproc Spark Sessions in Vertex AI.
It should be a template to facilitate the development of data processing pipelines using Spark, for specific sources and sinks, and allow the user to add the required transformations needed for the ML model development.

**Comment by shashank-google** [comment]
@nehamodgil @NiloFreitas 
Refer to this Jupyter notebook for inspiration: https://github.com/GoogleCloudPlatform/serverless-spark-workshop/blob/main/timeseries_forecasting/README.md

**Comment by NiloFreitas** [comment]
obsolete
