### ISSUE TITLE
[Jenkins][Python] Explore options to enable coverage report in Jenkins

### ISSUE THREAD

**Issue by surjits254** [GoogleCloudPlatform/dataproc-templates#408]
1. We have coverage report in jenkins for junits. eg: https://dataproctemplatesci.com/job/dataproc-templates-build/job/build-job-java/260/jacoco/
2. We need to explore how we can generate similar report for pyunits as well

**Comment by vanshaj-bhatia** [comment]
Done. Code Coverage and Test Run trends are live on the Jenkins python-build pipeline.
