### ISSUE TITLE
[jenkins] Create integration test automation for CassandraToGCS template

### ISSUE THREAD

**Issue by shashank-google** [GoogleCloudPlatform/dataproc-templates#417]

**Comment by tanyarw** [comment]
<img width="1908" alt="Screenshot 2023-01-12 at 6 35 06 PM" src="https://user-images.githubusercontent.com/51485771/212074063-af58703e-28c8-40ac-a9ca-3f7ee8c236a1.png">

Added CassandraToGCS test.
