### ISSUE TITLE
[jenkins] Create integration test automation for JDBCToGCS template

### ISSUE THREAD

**Issue by shashank-google** [GoogleCloudPlatform/dataproc-templates#425]

**Comment by hhasija** [comment]
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/106058340/205856147-dc4efd98-af07-41ad-86c0-529566f0bb7c.png">

**Comment by hhasija** [comment]
Added JDBC to GCS integration test as well in python jenkins.
