### ISSUE TITLE
[jenkins] Create integration test automation for JDBCToBQ template

### ISSUE THREAD

**Issue by shashank-google** [GoogleCloudPlatform/dataproc-templates#426]

**Comment by hhasija** [comment]
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/106058340/205830097-ae9eca0a-dc1c-4a0f-b35f-46ff82703209.png">

**Comment by hhasija** [comment]
Added Jenkins integration tests for JDBC to BigQuery as well
