### ISSUE TITLE
[Notebook] Pip Install Conflict cloud-tpu-client vs google-api-python-client

### ISSUE THREAD

**Issue by nj1973** [GoogleCloudPlatform/dataproc-templates#428]
When running Step 1 to install libraries in a new notebook instance we get the error below:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cloud-tpu-client 0.10 requires google-api-python-client==1.8.0, but you have google-api-python-client 1.12.11 which is incompatible.
```

This is the `pip` command in the notebook:
```
pip3 install --upgrade google-cloud-pipeline-components kfp --user -q
```

As this is the first step a user will run it gives a bad first impression.

**Comment by NiloFreitas** [comment]
On it

**Comment by NiloFreitas** [comment]
The installation of the specified packages do not fail because of this.
We need to install google-cloud-pipeline-components, and unfortunatelly cloud-tpu-client has a fixed dependency version and it is not up to date.
I contacted cloud-tpu-client maintainer to see if the package can be updated.

**Comment by NiloFreitas** [comment]
The is no maintainer for this package. I'll be closing this issue for now since this is not an actual error, just a warning.
