### ISSUE TITLE
[jenkins] Create Integration test for CassandraToBQ Python template 

### ISSUE THREAD

**Issue by anish97IND** [GoogleCloudPlatform/dataproc-templates#462]
New resource has to be deployed for the same in sandbox

**Comment by tanyarw** [comment]
<img width="1906" alt="Screenshot 2023-01-12 at 7 39 39 PM" src="https://user-images.githubusercontent.com/51485771/212088645-24500a51-a596-418d-95d0-1b1fcb90f665.png">

Added CassandraToBQ test.
