### ISSUE TITLE
OPT_PY_FILES typo in python/bin/start.sh

### ISSUE THREAD

**Issue by nj1973** [GoogleCloudPlatform/dataproc-templates#496]
The section of code in python/bin/start.sh that allows users to provide extra Python files via PY_FILES environment variable contains a mistake.

Suggested fix below:
```
 if [ -n "${PY_FILES}" ]; then
-  OPT_FILES="${OPT_PY_FILES},${PY_FILES}"
+  OPT_PY_FILES="${OPT_PY_FILES},${PY_FILES}"
 fi
```

**Comment by Raevat7** [comment]
Pull request merged to fix the issue .
https://github.com/GoogleCloudPlatform/dataproc-templates/pull/512
