### ISSUE TITLE
[Jenkins] Update python integration tests with enviroment variables

### ISSUE THREAD

**Issue by shashank-google** [GoogleCloudPlatform/dataproc-templates#515]
Similar to Java integration tests, update python integration tests with env variables

**Comment by tanyarw** [comment]
<img width="1505" alt="Screenshot 2023-01-23 at 7 36 44 PM" src="https://user-images.githubusercontent.com/51485771/214060119-f22b83ae-91f9-4ed6-85e5-1fd66713035f.png">


Added environment variables GCP_PROJECT, REGION, GCS_STAGING_LOCATION, SUBNET similar to java integration tests.
