### ISSUE TITLE
[Publishing] Create Gcloud commands and rest API for below templates, S3, JDBC, Text to Target BQ

### ISSUE THREAD

**Issue by surjits254** [GoogleCloudPlatform/dataproc-templates#519]
1. Java - S3ToBigQuery
2. Python - JDBCToBigQuery
3. Python - TextToBigQuery
Add the commands in : go/go/dataproc-gcp-documentation-internal document also contains commands for reference from other templates

**Comment by tanyarw** [comment]
Added to document

**Comment by tanyarw** [comment]
Will be impacted by #721

**Comment by tanyarw** [comment]
Pending review
