### ISSUE TITLE
[Publishing] Create Gcloud commands and rest API for below templates. Target JDBC

### ISSUE THREAD

**Issue by surjits254** [GoogleCloudPlatform/dataproc-templates#522]
1. Java - GCSToJDBC
2. Python - GCSToJDBC
3. Python - JDBCToJDBC
Add the commands in : go/go/dataproc-gcp-documentation-internal document also contains commands for reference from other templates

**Comment by tanyarw** [comment]
Added to document

**Comment by surjits254** [comment]
LGTM
