### ISSUE TITLE
[Publishing] Create Gcloud commands and rest API for below templates. Cassandra, Kafka, Mongo, PubSub to Target GCS

### ISSUE THREAD

**Issue by surjits254** [GoogleCloudPlatform/dataproc-templates#523]
1. Java - CassandraToGCS
2. Java - KafkaToGCS
3. Java - PubSubToGCS
4. Python - MongoToGCS
Add the commands in : go/go/dataproc-gcp-documentation-internal document also contains commands for reference from other templates

**Comment by poojabasker20** [comment]
commands added to doc

**Comment by poojabasker20** [comment]
Pending review
