### ISSUE TITLE
[Publishing] Create Gcloud commands and rest API for below templates. JDBC, Hive, Spanner, Bigquery to Target GCS

### ISSUE THREAD

**Issue by surjits254** [GoogleCloudPlatform/dataproc-templates#526]
1. Java - JDBCToGCS
2. Python - HiveToGCS
3. Java - SpannerToGCS
4. Python - BigQueryToGCS
Add the commands in : go/go/dataproc-gcp-documentation-internal document also contains commands for reference from other templates

**Comment by poojabasker20** [comment]
Added commands to the doc

**Comment by poojabasker20** [comment]
Pending review
