### ISSUE TITLE
[Test] : Add integration test for GCSToBigTable

### ISSUE THREAD

**Issue by shashank-google** [GoogleCloudPlatform/dataproc-templates#590]
Add integration test for GCSToBigTable Java Template

**Comment by saumyasinha-google** [comment]
<img width="1512" alt="Screenshot 2023-02-16 at 11 12 17 AM" src="https://user-images.githubusercontent.com/118509792/219278563-0d94afd0-a44d-4aa6-9704-64cbb66f8773.png">

**Comment by saumyasinha-google** [comment]
Added GCSToBigTable Test
