### ISSUE TITLE
[Spike] Explore the usage of PubSub Lite Spark Connector for Python template

### ISSUE THREAD

**Issue by vanshaj-bhatia** [GoogleCloudPlatform/dataproc-templates#594]
Explore the usage of the PubSub Lite Spark Connector for Python template because at the moment, there is no native Pub/Sub connector in Python that is equivalent to the Apache Bahir Pub/Sub connector in Java.

PySpark implementation reference: https://cloud.google.com/pubsub/lite/docs/write-messages-apache-spark

**Comment by arindam-google** [comment]
Created the Pubsublite to BigQuery python dataproc template using Spark Connector for Python. Please refer to the code in the [branch](https://github.com/GoogleCloudPlatform/dataproc-templates/tree/594-spike-explore-the-usage-of-pubsub-lite-spark-connector-for-python-template) for the implementation. Hence marking this issue as closed.
