### ISSUE TITLE
[Java Template] CassandraToBQ: empty validateInput method

### ISSUE THREAD

**Issue by mattfsmith** [GoogleCloudPlatform/dataproc-templates#595]
empty method.

Do we need to validate inputs (assumed yes). If we do, then let's fix this. 

public void validateInput() {} }

**Comment by saumyasinha-google** [comment]
Linked a Pull Request for this issue. Open to review.

**Comment by saumyasinha-google** [comment]
Dependant on PR https://github.com/GoogleCloudPlatform/dataproc-templates/pull/747 (currently under review) being merged
