### ISSUE TITLE
[Java Template] DataplexGCStoBQ: no test class

### ISSUE THREAD

**Issue by mattfsmith** [GoogleCloudPlatform/dataproc-templates#599]
Do we need a JUNIT test class? if so, let's create one.

**Comment by tanyarw** [comment]
This is already being worked on as seen in PR [#576](https://github.com/GoogleCloudPlatform/dataproc-templates/pull/576)

**Comment by mugdhapattnaik** [comment]
Closing this as PR #576 has been merged.
