### ISSUE TITLE
[java] [New Template] Kafka to GCS

### ISSUE THREAD

**Issue by shashank-google** [GoogleCloudPlatform/dataproc-templates#60]

**Comment by mandeeptrehan** [comment]
Suggestion: Kafka to GCS will make more sense if we merge data from Kafka in micro batches before storing to GCS. This way we can avoid too many files in the GCS bucket.

**Comment by shashank-google** [comment]
@nikhil6790 Any updates on this ?

**Comment by nikhil6790** [comment]
Hey Shashank, 
This should be completed this week. I am testing the changes with JSON schema passed as file to the template.

**Comment by nikhil6790** [comment]
> Suggestion: Kafka to GCS will make more sense if we merge data from Kafka in micro batches before storing to GCS. This way we can avoid too many files in the GCS bucket.

Thanks for the suggestion @mandeeptrehan . I have included provision to control triggers for micro-batches in the template
