### ISSUE TITLE
[Jenkins Integration Test] BigQueryToGCS : avro (binary output) : Create Test

### ISSUE THREAD

**Issue by mattfsmith** [GoogleCloudPlatform/dataproc-templates#605]
[Jenkins Integration Test] BigQueryToGCS : avro (binary output) : Create Test

**Comment by saumyasinha-google** [comment]
<img width="1285" alt="Screenshot 2023-02-28 at 1 37 46 PM" src="https://user-images.githubusercontent.com/118509792/221791987-9eae5b05-a4a4-42ce-8cef-87ade30c9914.png">

**Comment by saumyasinha-google** [comment]
Done.
