### ISSUE TITLE
[Jenkins Integration Test] SpannerToGCS : avro (binary output) : Create Test

### ISSUE THREAD

**Issue by mattfsmith** [GoogleCloudPlatform/dataproc-templates#609]
[Jenkins Integration Test] SpannerToGCS : avro (binary output) : Create Test

**Comment by hhasija** [comment]
Done

<img width="1725" alt="image" src="https://user-images.githubusercontent.com/106058340/220709207-20e6fb63-a28f-4e36-b7bb-e0dd0f0ba280.png">
