### ISSUE TITLE
[Jenkins Integration Test] SpannerToGCS : csv output : Create Test

### ISSUE THREAD

**Issue by mattfsmith** [GoogleCloudPlatform/dataproc-templates#610]
[Jenkins Integration Test] SpannerToGCS : csv output : Create Test

**Comment by hhasija** [comment]
Done 

<img width="1725" alt="image" src="https://user-images.githubusercontent.com/106058340/220709331-0e1ef7c7-e04a-4ad6-904a-243778ee05b8.png">
