### ISSUE TITLE
[Jenkins Integration Test] GCStoBigquery : csv output : Create Test

### ISSUE THREAD

**Issue by mattfsmith** [GoogleCloudPlatform/dataproc-templates#611]
[Jenkins Integration Test] GCStoBigquery : csv output : Create Test

**Comment by hhasija** [comment]
Done 

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/106058340/224531557-2af67bfb-1a90-430f-b924-446c2cbc1400.png">
