### ISSUE TITLE
[Jenkins Integration Test] HbaseToGCS : csv output : Create Test

### ISSUE THREAD

**Issue by mattfsmith** [GoogleCloudPlatform/dataproc-templates#612]
[Jenkins Integration Test] HbaseToGCS : csv output : Create Test

**Comment by hhasija** [comment]
Done 

<img width="1725" alt="image" src="https://user-images.githubusercontent.com/106058340/220731299-f0513a05-745d-46b5-a3c7-6ef675788630.png">
