### ISSUE TITLE
[Jenkins Integration Test] HbaseToGCS : avro (binary output) : Create Test

### ISSUE THREAD

**Issue by mattfsmith** [GoogleCloudPlatform/dataproc-templates#613]
[Jenkins Integration Test] HbaseToGCS : avro (binary output) : Create Test

**Comment by hhasija** [comment]
Done

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/106058340/224504207-a6a4dd36-12fa-493b-b65e-beed4957892b.png">
