### ISSUE TITLE
[Jenkins Integration Test] JDBCToGCS : avro (binary output) : Create Test

### ISSUE THREAD

**Issue by mattfsmith** [GoogleCloudPlatform/dataproc-templates#614]
[Jenkins Integration Test] JDBCToGCS : avro (binary output) : Create Test

**Comment by hhasija** [comment]
Done

<img width="1725" alt="image" src="https://user-images.githubusercontent.com/106058340/220642855-50989283-f63d-4ff0-ab37-53b89f070974.png">
