### ISSUE TITLE
[Jenkins Integration Test] PubSubToGCS : csv output : Create Test

### ISSUE THREAD

**Issue by mattfsmith** [GoogleCloudPlatform/dataproc-templates#619]
[Jenkins Integration Test] PubSubToGCS : csv output : Create Test

**Comment by ClementineJoe** [comment]
Requesting Updates

**Comment by poojabasker20** [comment]
PubSubToGCS does not support CSV as of now. Still in discussion with @vanshaj-bhatia regarding this.

**Comment by poojabasker20** [comment]
Closing issue for now as PubSubToGCS does not support CSV.
