### ISSUE TITLE
New Template: Kafka to PubSub

### ISSUE THREAD

**Issue by shashank-google** [GoogleCloudPlatform/dataproc-templates#62]

**Comment by bipinupd** [comment]
@shashank-google can you assign to me ....

**Comment by shashank-google** [comment]
Done

**Comment by shashank-google** [comment]
@bipinupd if you have made no progress on the template plase unassign yourself.

**Comment by shashank-google** [comment]
@vanshaj-bhatia bumping this up, any updates?

**Comment by shashank-google** [comment]
@vanshaj-bhatia can you please link the branch which has code changes for this.
Please sync with @hhasija for advise.

**Comment by vanshaj-bhatia** [comment]
By making use of ForEachWriter and Java Client API for publishing messages to PubSub able achieve throughput of as high as 1967.45k messages per second.
