### ISSUE TITLE
[Jenkins Integration Test] KafkaToGCS : csv output : Create Test

### ISSUE THREAD

**Issue by mattfsmith** [GoogleCloudPlatform/dataproc-templates#620]
[Jenkins Integration Test] KafkaToGCS : csv output : Create Test

**Comment by hhasija** [comment]
Done 

<img width="1725" alt="image" src="https://user-images.githubusercontent.com/106058340/220728321-19c79a7b-63cb-4c41-b38b-b048db3b5032.png">
