### ISSUE TITLE
[Jenkins Integration Test] GCStoGCS : avro (binary output) : Create Test

### ISSUE THREAD

**Issue by mattfsmith** [GoogleCloudPlatform/dataproc-templates#622]
[Jenkins Integration Test] GCStoGCS : avro (binary output) : Create Test

**Comment by hhasija** [comment]
Done 

<img width="1725" alt="image" src="https://user-images.githubusercontent.com/106058340/220849488-7f2c3f02-2226-4b33-bdc0-487f9227a89e.png">
