### ISSUE TITLE
[Jenkins Integration Test] GCStoGCS : csv output : Create Test

### ISSUE THREAD

**Issue by mattfsmith** [GoogleCloudPlatform/dataproc-templates#623]
[Jenkins Integration Test] GCStoGCS : csv output : Create Test

**Comment by hhasija** [comment]
Done 

<img width="1725" alt="image" src="https://user-images.githubusercontent.com/106058340/220849512-b595984b-834b-45b5-9194-17b81e6e71d7.png">
