### ISSUE TITLE
[Documentation][Enhancement] Update GCS to Cloud Storage in Readme

### ISSUE THREAD

**Issue by surjits254** [GoogleCloudPlatform/dataproc-templates#639]
Update documentation for below Java and Python templates to change GCS to Cloud storage to conform with approved branding names:
1. GCS to BigQuery
2. JDBC to GCS
3. Hive to GCS

**Comment by nj1973** [comment]
PR https://github.com/GoogleCloudPlatform/dataproc-templates/pull/640 changes all of the Python GCS templates and README files so it would be a good idea to wait for that to be merged before making Python changes for this issue.

**Comment by violetautumn** [comment]
Hi @surjits254, is this issue up for being taken now?

**Comment by surjits254** [comment]
@violetautumn yes please go ahead

**Comment by violetautumn** [comment]
Thanks @surjits254! 

I wanted to confirm one thing, the update needs to be made in all templates in which GCS is involved, or just the ones that are mentioned in the issue description?

**Comment by violetautumn** [comment]
To add to the context, if we are to update documentation involving all the templates where GCS is present, it would entail updating the following readme files:

- [Six sections in the GCS readme](https://github.com/GoogleCloudPlatform/dataproc-templates/blob/main/java/src/main/java/com/google/cloud/dataproc/templates/gcs/README.md)
- [HBase to GCS readme](https://github.com/GoogleCloudPlatform/dataproc-templates/blob/main/java/src/main/java/com/google/cloud/dataproc/templates/hbase/README.md#1-hbase-to-gcs)
- [Hive to GCS readme](https://github.com/GoogleCloudPlatform/dataproc-templates/blob/main/java/src/main/java/com/google/cloud/dataproc/templates/hive/README.md#2-hive-to-gcs)
- [JDBC to GCS readme](https://github.com/GoogleCloudPlatform/dataproc-templates/blob/main/java/src/main/java/com/google/cloud/dataproc/templates/jdbc/README.md#2-jdbc-to-gcs)
- [Kafka to GCS readme](https://github.com/GoogleCloudPlatform/dataproc-templates/blob/main/java/src/main/java/com/google/cloud/dataproc/templates/kafka/README.md#2-kafka-to-gcs)
- [Pubsub to GCS readme](https://github.com/GoogleCloudPlatform/dataproc-templates/blob/main/java/src/main/java/com/google/cloud/dataproc/templates/pubsub/README.md#2-pubsub-to-gcs)
- [Snowflake to GCS readme](https://github.com/GoogleCloudPlatform/dataproc-templates/blob/main/java/src/main/java/com/google/cloud/dataproc/templates/snowflake/README.md#1-snowflake-to-gcs)

@surjits254 Kindly let me know if I am missing something and I'll raise a PR accordingly 🙌

**Comment by surjits254** [comment]
Yes please go ahead, we need this for both Java and Python templates

**Comment by violetautumn** [comment]
Closing this issue as the PR has been merged.
