### ISSUE TITLE
PyPI package changed from 0.0.3 to 0.0.1

### ISSUE THREAD

**Issue by voutilad** [GoogleCloudPlatform/dataproc-templates#641]
Just noticed a project I was working on broke because as of today the hosted PyPI release reverted to 0.0.1. (see https://pypi.org/project/google-dataproc-templates/#history)

Was this intentional?

**Comment by ankuljain09** [comment]
Hi @voutilad. Yes the release was older and was not in sync with the repo. Hence, it had to be re-versioned. 
We would like to support your project as we move along, so could you please let us know a bit about your project and how you are using Dataproc Templates pypi package?

**Comment by voutilad** [comment]
> Hi @voutilad. Yes the release was older and was not in sync with the repo. Hence, it had to be re-versioned. We would like to support your project as we move along, so could you please let us know a bit about your project and how you are using Dataproc Templates pypi package?

Sure. I'm the primary author of Neo4j's recently released [integration ](https://github.com/neo4j-field/bigquery-connector)with BigQuery. I leveraged the Dataproc Templates as a way to structure the project.
