### ISSUE TITLE
[Java Template] PubSubLiteToGCS

### ISSUE THREAD

**Issue by vanshaj-bhatia** [GoogleCloudPlatform/dataproc-templates#654]
ref. [[Spike] Explore the usage of PubSub Lite Spark Connector for new Java templates](https://github.com/GoogleCloudPlatform/dataproc-templates/issues/593)

**Comment by saumyasinha-google** [comment]
Done with the template. Unit tests are left.

**Comment by shashank-google** [comment]
PSL related templates are deprioritized, closing the issue.
