### ISSUE TITLE
[Java Template] PubSubLiteToBigTable

### ISSUE THREAD

**Issue by vanshaj-bhatia** [GoogleCloudPlatform/dataproc-templates#655]
ref. [[Spike] Explore the usage of PubSub Lite Spark Connector for new Java templates](https://github.com/GoogleCloudPlatform/dataproc-templates/issues/593)

**Comment by balajiss2** [comment]
Exploring on the connector. Will update the findings at the earliest

**Comment by balajiss2** [comment]
Template completed. Testing in progress. should be complete in a day or two
