### ISSUE TITLE
[Java Template] PubSubLiteToBigQuery

### ISSUE THREAD

**Issue by vanshaj-bhatia** [GoogleCloudPlatform/dataproc-templates#656]
ref. [[Spike] Explore the usage of PubSub Lite Spark Connector for new Java templates](https://github.com/GoogleCloudPlatform/dataproc-templates/issues/593)

**Comment by vanshaj-bhatia** [comment]
Template development completed. Writes to BQ are failing, debugging in-progress.

**Comment by vanshaj-bhatia** [comment]
This requirement will be revisited in the following quarter.

**Comment by shashank-google** [comment]
We should build more templates on PSL for now. Closing this.
