### ISSUE TITLE
[Notebook] Fix errors due to new runtime version with Scala 2.13 instead of 2.12

### ISSUE THREAD

**Issue by NiloFreitas** [GoogleCloudPlatform/dataproc-templates#665]
The new default runtime of Dataproc Serverless (version 2) uses Scala 2.13, which makes some dependencies, compiled using Scala 2.12 to throw errors, like Caused by: java.lang.NoClassDefFoundError: scala/Serializable.

For now, we need to set the specific runtime version when submitting jobs, to use runtime version 1.

We need to update all notebooks to pass the **runtime_config_version** when submitting the job. Ref: https://google-cloud-pipeline-components.readthedocs.io/en/google-cloud-pipeline-components-1.0.6/google_cloud_pipeline_components.experimental.dataproc.html

Runtime versions: https://cloud.google.com/dataproc-serverless/docs/concepts/versions/spark-runtime-versions

**Comment by surjits254** [comment]
Hi @NiloFreitas , just to be on same page, version should be 1.1
