### ISSUE TITLE
New Template: HDFS to GCS

### ISSUE THREAD

**Issue by shashank-google** [GoogleCloudPlatform/dataproc-templates#72]
We need to create a template facilitating copying of files from HDFS to GCS.
It should allow:
1. Copy files recursively from source directory, filter based on a regex.
2. [Optional] Max network bandwidth
3. [Optional] Ability to fetch incrementally changed files (similar to rsync).
4. [Optional] Ability to discard some of the files via regex. 
5. [Optional] File conversion (csv to ORC/Parquet etc) - P3
6. Handle security authentication for source cluster. (Ex configurable for kerberos keytab etc)

**Comment by ajayydv** [comment]
4. [Optional] File conversion (csv to ORC/Parquet etc) - P3
5. Handle security authentication for source cluster. (Ex configurable for kerberos keytab etc)

**Comment by shashank-google** [comment]
There is a similar 3rd party tool: https://github.com/CoxAutomotiveDataSolutions/spark-distcp

**Comment by shashank-google** [comment]
No longer needed.
