### ISSUE TITLE
[Java] [Python] Deprecate text to BigQuery templates

### ISSUE THREAD

**Issue by nj1973** [GoogleCloudPlatform/dataproc-templates#721]
The text to BigQuery templates have been superceded by the GCS to BigQuery templates which cover the same CSV functionality but also support formats other than CSV.

In PR https://github.com/GoogleCloudPlatform/dataproc-templates/pull/695/commits/8aaad3fc968a27385f376229e5aa17e0f90879d6#r1140261859 we made the decision to deprecate these. This issue cannot be actioned until the related PR has been merged.

Don't forget to also remove unit tests, README entry and check for any integration tests in Jenkins.

**Comment by surjits254** [comment]
added deprecation in readme. Will be deprecated in Q1 2025
