### ISSUE TITLE
[publish] Blog on Mongo To GCS 

### ISSUE THREAD

**Issue by hhasija** [GoogleCloudPlatform/dataproc-templates#733]

**Comment by saumyasinha-google** [comment]
In Progress

**Comment by shrutimalgatti** [comment]
re assigning to myself after checking with saumya

**Comment by shrutimalgatti** [comment]
Blog submitted for review https://medium.com/google-cloud/migrating-data-from-mongo-to-gcs-using-java-and-dataproc-serverless-template-390500481804

**Comment by shrutimalgatti** [comment]
blog published https://medium.com/google-cloud/migrating-data-from-mongo-to-gcs-using-java-and-dataproc-serverless-template-390500481804
