### ISSUE TITLE
[Python] Add unit tests for PUBSUBLITETOGCS template

### ISSUE THREAD

**Issue by NiloFreitas** [GoogleCloudPlatform/dataproc-templates#752]
PUBSUBLITETOGCS does not have proper unit tests. Consider looking at the PUBSUBLITETOBIGTABLE unit tests to help developing the PUBSUBLITETOGCS unit tests

**Comment by tanyarw** [comment]
Pub/Sub Lite to GCS Template is failing with **FileFormatWriter** error. In discussion with @vanshaj-bhatia

**Comment by tanyarw** [comment]
PSL to GCS templates are failing. This requirement will be revisited in the following quarter.
