### ISSUE TITLE
[Notebook] PostgreSQL to BigQuery

### ISSUE THREAD

**Issue by NiloFreitas** [GoogleCloudPlatform/dataproc-templates#756]
Create Jupyter Notebook solution for migrating PostgreSQL to BigQuery using Dataproc Templates
Similar to MySQL To BigQuery notebook

**Comment by gabrielacorona** [comment]
Development started, adding the finishing touches to the code so that it can be run programmatically with python

**Comment by NiloFreitas** [comment]
Closed by PR [#805](https://github.com/GoogleCloudPlatform/dataproc-templates/pull/805)
