### ISSUE TITLE
Text2BQ template

### ISSUE THREAD

**Issue by ajayydv** [GoogleCloudPlatform/dataproc-templates#78]
Update existing GCS2BigQuery template (or create New template) for Text2BQ. Things to consider:

1. Compression  (gzip and other codecs as well)
2. Performance (parallel processing)
3. Delimiter (handle CSV, TSV and other formats based on configurable delimiter.)

**Comment by shashank-google** [comment]
@shradha-tyagi Any updates on the same ?

**Comment by shradha-tyagi** [comment]
@shashank-google I was not able to make much progress this week. Will be working on it starting today.

**Comment by shradha-tyagi** [comment]
@ajayydv / @shashank-google Please confirm if we can close this issue.

**Comment by shashank-google** [comment]
Yes we can close it.
