### ISSUE TITLE
Need custom delimiter option for CSV file on GCStoBigquery dataproc template

### ISSUE THREAD

**Issue by ppatel54** [GoogleCloudPlatform/dataproc-templates#792]
The GCStoBigquery dataproc template currently uses default delimiter (comma) when it comes to CSV files. Need to enhance the template to allow user defined delimiters as an optional argument.

**Comment by surjits254** [comment]
Hi @ppatel54 we have python template
https://github.com/GoogleCloudPlatform/dataproc-templates/tree/main/python/dataproc_templates/gcs#gcs-to-bigquery
which has gcs.bigquery.input.sep for delimiter with other csv related parameters. Let me know if this helps

**Comment by shashank-google** [comment]
@ppatel54 please confirm

**Comment by shubhampathakk** [comment]
Hi @surjits254, if this issue is still open can I assign it to myself?

**Comment by ppatel54** [comment]
This can be ignored. Python template has the option.

Thanks,
Palak Patel
________________________________

**Comment by shubhampathakk** [comment]
@ppatel54 so can I close this issue if nothing else is required?

**Comment by ppatel54** [comment]
Yes, pls close the request.

Sent via the Samsung Galaxy S23+ 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
