### ISSUE TITLE
[publish] Blog on Redshift To GCS - Java

### ISSUE THREAD

**Issue by hhasija** [GoogleCloudPlatform/dataproc-templates#816]

**Comment by violetautumn** [comment]
Hi @hhasija, came across this blog that Shivam Somani has written about [migrating data from Redshift to BQ](https://medium.com/google-cloud/exporting-data-from-redshift-to-gcs-using-gcp-dataproc-serverless-and-pyspark-9ab78de11405) in Sept 2022. 

I think we can close this issue? Also, I wanted to ask if I can raise a PR updating the blog link for the same in the main readme file?

**Comment by forksumit** [comment]
Blog published: https://medium.com/@sumi7/exporting-data-from-redshift-to-gcs-using-gcp-dataproc-serverless-java-5b82044d78e7

Awaiting approval to add to `Google Cloud - Community`
