### ISSUE TITLE
[Enhancement] Update Python start.sh script

### ISSUE THREAD

**Issue by surjits254** [GoogleCloudPlatform/dataproc-templates#820]
Update start.sh script to accept custom SA or use default SA. Also updated execution command from "gcloud beta dataproc batches submit pyspark" to "gcloud dataproc batches submit pyspark"

**Comment by anish97IND** [comment]
Created a similar issue on java side (https://github.com/GoogleCloudPlatform/dataproc-templates/issues/910)- have we decided on any approach here, because I had something in mind which I implemented for a live project.

**Comment by surjits254** [comment]
Yes, please work with @shubhamgoogle . Thanks

**Comment by rajc242** [comment]
It's already completed.
