### ISSUE TITLE
Publishing : Public post for JDBC related templates usage

### ISSUE THREAD

**Issue by snrssc** [GoogleCloudPlatform/dataproc-templates#85]
Publish a post/blog on how to use Dataproc Serverless JDBC related templates

**Comment by shashank-google** [comment]
Published one blogpost here: https://agarwalsh.medium.com/fast-export-large-database-tables-using-gcp-serverless-dataproc-spark-bb32b1260268

**Comment by shashank-google** [comment]
published.
