### ISSUE TITLE
[Publishing][Python] Blog for Kafka to GCS Template

### ISSUE THREAD

**Issue by surjits254** [GoogleCloudPlatform/dataproc-templates#866]

**Comment by shubhampathakk** [comment]
submitted for review: https://medium.com/google-cloud/kafka-to-gcs-using-dataproc-serverless-python-template-750ed218a5cc

**Comment by shubhampathakk** [comment]
Posted the blog: https://medium.com/google-cloud/kafka-to-gcs-using-dataproc-serverless-python-template-750ed218a5cc
