### ISSUE TITLE
[Notebook] Update HiveToBQ notebook to use Spark Serveless Sessions

### ISSUE THREAD

**Issue by shashank-google** [GoogleCloudPlatform/dataproc-templates#884]
Overwrite the notebook to run dataproc via sessions and not batches. With the dataproc-jupyter-plugin, a dataproc session can be used as kernel

**Comment by rajc242** [comment]
Our notebook is already using serverless dataproc only. Given plugin is helping people to more interactively run their cells directly to serverless dataproc. It will keep cluster up and running till either you explicitly shutdown your kernel or dataproc serverless timeout meet which will trigger shutdown.
