### ISSUE TITLE
[Publishing] [Java] Blog for Text to BigQuery

### ISSUE THREAD

**Issue by violetautumn** [GoogleCloudPlatform/dataproc-templates#916]
Publish a blog on exporting data from [Text (GCS) to BigQuery](https://github.com/GoogleCloudPlatform/dataproc-templates/tree/main/java/src/main/java/com/google/cloud/dataproc/templates/gcs#7-text-to-bigquery) using Dataproc Serverless (Java)

**Comment by vanshaj-bhatia** [comment]
Hello @violetautumn, We plan to decommission the TextToBQ template soon. I believe it would be beneficial to refrain from working on the blog related to this template. @surjits254, what are your thoughts? Should we consider closing this issue as not planned?

**Comment by violetautumn** [comment]
Hi @vanshaj-bhatia @surjits254, can you please let me know if any decision has been finalized? I'll close the issue if we're going ahead with the decommissioning, thanks

**Comment by rajc242** [comment]
It is deprecated.
