### ISSUE TITLE
[Publishing] [Java] Blog for CassandraToBigQuery

### ISSUE THREAD

**Issue by shrutimalgatti** [GoogleCloudPlatform/dataproc-templates#918]
Publish a blog on exporting data from CassandraToBigQuery using Dataproc serverless java

**Comment by shrutimalgatti** [comment]
Blog post in review https://medium.com/google-cloud/migrate-data-from-cassandra-to-bigquery-using-java-and-dataproc-serverless-926110c44413

**Comment by vanshaj-bhatia** [comment]
@shrutimalgatti If it's reviewed. Please raise a PR to add this to README files.
