### ISSUE TITLE
Refactor BaseTemplate template names to use Java naming practice

### ISSUE THREAD

**Issue by franklinWhaite** [GoogleCloudPlatform/dataproc-templates#98]
Refactor [BaseTemplate template names](https://github.com/GoogleCloudPlatform/dataproc-templates/blob/main/src/main/java/com/google/cloud/dataproc/templates/BaseTemplate.java#L25-L37) to use Java naming practice, e.g. BIGQUERYTOGCS -> BIGQUERY_TO_GCS

**Comment by shashank-google** [comment]
we are deciding not to do this.
