### ISSUE TITLE
[Automation] Use same java build across all the integration tests in a given PR / Merge

### ISSUE THREAD

**Issue by shashank-google** [GoogleCloudPlatform/dataproc-templates#981]
Currently Java build take 15-30 mins (depending on jenkins VM CPU availability).
And build is created three times (1. build job 2. integration-tests-java 3. ui-integration-tests)

We should make all the integration tests downstream to build job and reconfigure them to use same build (if exists). Hence improving the runtime of all the tests.

**Comment by rajc242** [comment]
AWS/S3 dependency removal has reduced java build time.
