### ISSUE TITLE
[Enhancemement] Upgrade ES templates to version 1.2

### ISSUE THREAD

**Issue by surjits254** [GoogleCloudPlatform/dataproc-templates#992]

**Comment by surjits254** [comment]
Hi Anuj,
Sure, I assigned Raj to merge this. We will let you know if ES testing with
1.2 is required from your end if not you can focus on just the enchancements

Thanks,
Surjit

**Comment by rajc242** [comment]
@rohilla-anuj  I merged pull request. I have one elasticsearch instance up and running where Elasticsearch to GCS jenkins test has been added. Please go ahead with your work now.

**Comment by rohilla-anuj** [comment]
@surjits254 we are good to go with the version upgrade.
